#!/bin/bash

set -e

platform="${1}"
hostname="${2}"
targetDevice="${3}"
filesystem="fat32"
blocksPerOverlay=8

if [ "${platform}" = "" ] || [ "${hostname}" = "" ]; then
	echo "Usage ${0} <ArduinoSamd21|AgonLight2> <hostname> [target device]" >&2
	exit 1
fi

if [ "${platform}" = "ArduinoSamd21" ]; then
	compile="arm-none-eabi-gcc"
	link="arm-none-eabi-ld"
	objcopy="arm-none-eabi-objcopy"
	objdump="arm-none-eabi-objdump"
	size="arm-none-eabi-size"
	linkerScript="NanoOsArduinoSamd21.ld"
	extraIncludes=""
elif [ "${platform}" = "AgonLight2" ]; then
	agonHome="${HOME}/agondev"
	agonDevBin="${agonHome}/bin"
	compile="${agonDevBin}/ez80-none-elf-clang"
	link="${agonDevBin}/ez80-none-elf-ld"
	objcopy="${agonDevBin}/ez80-none-elf-objcopy"
	objdump="${agonDevBin}/ez80-none-elf-objdump"
	size="${agonDevBin}/ez80-none-elf-size"
	linkerScript="NanoOsAgonLight2.ld"
	clangResourceDir="$("${compile}" --print-resource-dir 2>/dev/null)"
	extraIncludes="-I${agonHome}/include"
	if [ -n "${clangResourceDir}" ]; then
		extraIncludes="${extraIncludes} -I${clangResourceDir}/include"
	fi
else
	echo "ERROR: Unknown platform '${platform}'.  Must be 'ArduinoSamd21' or 'AgonLight2'." >&2
	exit 1
fi

echo "Building applications..."
make -j $(nproc) -C usr/src clean
make -j $(nproc) -C usr/src COMPILE="${compile}" LINK="${link}" \
	OBJCOPY="${objcopy}" OBJDUMP="${objdump}" \
	SIZE="${size}" LINKER_SCRIPT="${linkerScript}" \
	EXTRA_INCLUDES="${extraIncludes}" overlays

echo ""
echo "Build complete."

if [ "${targetDevice}" != "" ]; then
	# Make a temporary mountpoint
	mountDir="$(mktemp -d)"
	trap "rm -rf \"${mountDir}\"" ERR EXIT

	echo '2048,,0c' | sudo sfdisk "${targetDevice}"
	sudo mkfs.vfat -F 32 "${targetDevice}p1" -n NanoOs
	sudo mount "${targetDevice}p1" "${mountDir}"
	sudo mkdir -p "${mountDir}/usr"
	sudo cp -r usr/bin "${mountDir}/usr"
	sudo cp -r usr/lib "${mountDir}/usr"
	sudo mkdir -p "${mountDir}/etc"
	sudo bash -c "printf \"${hostname}\" >\"${mountDir}/etc/hostname\""
	sudo bash -c "printf '\\s \\\r \\\n \\l\n\n' >\"${mountDir}/etc/issue\""
	sudo umount "${mountDir}"

	blockOverlays="$(ls usr/lib/{filesystem,${filesystem}}/*)"
	for blockOverlay in ${blockOverlays}; do
		overlayId="$(basename "${blockOverlay}" .overlay)"
		startBlock=$(( (overlayId * blocksPerOverlay) + 1 ))
		sudo dd if="${blockOverlay}" of="${targetDevice}" bs=512 \
			seek=${startBlock}
	done
fi
