#!/bin/bash

set -e

hostname="${1}"
targetDevice="${2}"
filesystem="fat32"
blocksPerOverlay=8

if [ "${hostname}" = "" ]; then
	echo "Usage ${0} <hostname> [target device]" >&2
	exit 1
fi

echo "Building applications..."
make -j $(nproc) -C usr/src clean
make -j $(nproc) -C usr/src COMPILE=arm-none-eabi-gcc LINK=arm-none-eabi-ld \
	OBJCOPY=arm-none-eabi-objcopy OBJDUMP=arm-none-eabi-objdump \
	SIZE=arm-none-eabi-size LINKER_SCRIPT=NanoOs.ld overlays

echo ""
echo "Build complete."

if [ "${targetDevice}" != "" ]; then
	# Make a temporary mountpoint
	mountDir="$(mktemp -d)"
	trap "rm -rf \"${mountDir}\"" ERR EXIT

	echo '2048,,0c' | sudo sfdisk "${targetDevice}"
	sudo mkfs.vfat -F 32 "${targetDevice}p1" -n NanoOs
	sudo mount "${targetDevice}p1" "${mountDir}"
	sudo mkdir -p "${mountDir}/usr"
	sudo cp -r usr/bin "${mountDir}/usr"
	sudo cp -r usr/lib "${mountDir}/usr"
	sudo mkdir -p "${mountDir}/etc"
	sudo bash -c "printf \"${hostname}\" >\"${mountDir}/etc/hostname\""
	sudo bash -c "printf '\\s \\\r \\\n \\l\n\n' >\"${mountDir}/etc/issue\""
	sudo umount "${mountDir}"
fi

blockOverlays="$(ls usr/lib/{filesystem,${filesystem}}/*)"
for blockOverlay in ${blockOverlays}; do
	overlayId="$(basename "${blockOverlay}" .overlay)"
	startBlock=$(( (overlayId * blocksPerOverlay) + 1 ))
	sudo dd if="${blockOverlay}" of="${targetDevice}" bs=512 \
		seek=${startBlock}
done
